name: stock_manager
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  connectivity_plus: ^2.2.0
  google_fonts: ^2.1.1
  go_router: ^3.0.1
  rxdart: ^0.27.3
  uuid: ^3.0.5
  timezone: ^0.8.0
  gsheets: ^0.3.2
  qr_code_scanner: ^0.6.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  flutter_secure_storage: ^5.0.2
  badges: ^2.0.2
  barcode_widget: ^2.0.2
  pdf: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  logger: ^1.1.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo.png
    - assets/open_sans.ttf

  fonts:
    - family: open_sans
      fonts:
        - asset: assets/open_sans.ttf
