name: qr_sheet_stock_manager
description: for stock management with google sheet & qr code.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  flutter_secure_storage: ^5.0.2
  connectivity_plus: ^2.2.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  google_fonts: ^2.1.1
  go_router: ^3.0.1
  rxdart: ^0.27.3
  uuid: ^3.0.5
  timezone: ^0.8.0
  badges: ^2.0.2
  flutter_markdown: ^0.6.9
  url_launcher: ^6.0.20
  gsheets: ^0.3.2
  qr_code_scanner: ^0.7.0
  barcode_widget: ^2.0.2
  pdf: ^3.7.1
  in_app_purchase: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.3
  logger: ^1.1.0
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.0.5

#  flutter pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  color: "#A3A3A3"
  color_dark: "#404040"
#  image
#  image_dark
#  branding: "assets/app_logo.png"
#  branding_mode: bottom

#  flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_logo.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/manual/
    - assets/app_logo.png
    - assets/CascadiaMonoPL.ttf

  fonts:
    - family: CascadiaMonoPL
      fonts:
        - asset: assets/CascadiaMonoPL.ttf
